/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author boki
 */
public class ClanoviPregledIznajmljenihKnjigaGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClanoviPregledIznajmljenihKnjigaGUI
     */
    public ClanoviPregledIznajmljenihKnjigaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Naslov = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Pisac = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Zanr = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        Ok = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        Naslov.setText("Naslov");
        getContentPane().add(Naslov);
        Naslov.setBounds(30, 34, 60, 20);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 30, 220, 30);

        Pisac.setText("Pisac");
        getContentPane().add(Pisac);
        Pisac.setBounds(20, 110, 60, 20);

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(80, 110, 220, 30);

        Zanr.setText("Zanr");
        getContentPane().add(Zanr);
        Zanr.setBounds(20, 184, 60, 20);

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(80, 180, 220, 30);

        Ok.setText("OK");
        getContentPane().add(Ok);
        Ok.setBounds(70, 253, 90, 30);

        Cancel.setText("Cancel");
        getContentPane().add(Cancel);
        Cancel.setBounds(220, 253, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClanoviPregledIznajmljenihKnjigaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClanoviPregledIznajmljenihKnjigaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClanoviPregledIznajmljenihKnjigaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClanoviPregledIznajmljenihKnjigaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClanoviPregledIznajmljenihKnjigaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Naslov;
    private javax.swing.JButton Ok;
    private javax.swing.JLabel Pisac;
    private javax.swing.JLabel Zanr;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
