/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;
import view.*;
import javax.swing.*;

/**
 *
 * @author boki
 */
public class MainMenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuGUI
     */
    public MainMenuGUI() {
        initComponents();
        inicijalizujFrame(this, 400, 300, null, "Biblioteka");

    }

    private javax.swing.JFrame inicijalizujFrame(javax.swing.JFrame frame, int width, int height, Component relativeTo, String title) {
        frame.setSize(width, height);
        frame.setResizable(false);
        frame.setLocationRelativeTo(relativeTo);
        frame.setVisible(true);
        frame.setTitle(title);
        frame.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Biblioteka.png")));
        return frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        Clanovi = new javax.swing.JMenu();
        ClanoviNoviClan = new javax.swing.JMenuItem();
        PregledRegistrovanihClanova = new javax.swing.JMenuItem();
        Knjige = new javax.swing.JMenu();
        NovaKnjiga = new javax.swing.JMenuItem();
        PregledKnjiga = new javax.swing.JMenuItem();
        KnjigePregledIznajmljenihKnjiga = new javax.swing.JMenuItem();
        NovaKategorijaKnjiga = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        razduzivanjeKnjigeMenuItem = new javax.swing.JMenuItem();
        Pisci = new javax.swing.JMenu();
        NoviPisac = new javax.swing.JMenuItem();
        PregledPisaca = new javax.swing.JMenuItem();
        PregledKnjigaPoPiscu = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Clanovi.setText("Clanovi");

        ClanoviNoviClan.setIcon(new javax.swing.ImageIcon("C:\\Users\\boki\\Downloads\\user.png")); // NOI18N
        ClanoviNoviClan.setText("Novi Clan");
        ClanoviNoviClan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ClanoviNoviClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClanoviNoviClanActionPerformed(evt);
            }
        });
        Clanovi.add(ClanoviNoviClan);

        PregledRegistrovanihClanova.setIcon(new javax.swing.ImageIcon("C:\\Users\\boki\\Downloads\\users.png")); // NOI18N
        PregledRegistrovanihClanova.setText("Pregled Registrovanih Clanova");
        PregledRegistrovanihClanova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PregledRegistrovanihClanovaActionPerformed(evt);
            }
        });
        Clanovi.add(PregledRegistrovanihClanova);

        jMenuBar1.add(Clanovi);

        Knjige.setText("Knjige");
        Knjige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnjigeActionPerformed(evt);
            }
        });

        NovaKnjiga.setIcon(new javax.swing.ImageIcon("C:\\Users\\boki\\Downloads\\buk.png")); // NOI18N
        NovaKnjiga.setText("Nova Knjiga");
        NovaKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaKnjigaActionPerformed(evt);
            }
        });
        Knjige.add(NovaKnjiga);

        PregledKnjiga.setIcon(new javax.swing.ImageIcon("C:\\Users\\boki\\Downloads\\list.png")); // NOI18N
        PregledKnjiga.setText("Pregled Knjiga");
        PregledKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PregledKnjigaActionPerformed(evt);
            }
        });
        Knjige.add(PregledKnjiga);

        KnjigePregledIznajmljenihKnjiga.setIcon(new javax.swing.ImageIcon("C:\\Users\\boki\\Downloads\\list.png")); // NOI18N
        KnjigePregledIznajmljenihKnjiga.setText("Pregled Iznajmljenih Knjiga");
        KnjigePregledIznajmljenihKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnjigePregledIznajmljenihKnjigaActionPerformed(evt);
            }
        });
        Knjige.add(KnjigePregledIznajmljenihKnjiga);

        NovaKategorijaKnjiga.setIcon(new javax.swing.ImageIcon("C:\\Users\\boki\\Downloads\\blue.png")); // NOI18N
        NovaKategorijaKnjiga.setText("Nova Kategorija Knjiga");
        NovaKategorijaKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaKategorijaKnjigaActionPerformed(evt);
            }
        });
        Knjige.add(NovaKategorijaKnjiga);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/1459100361_bookcase.png"))); // NOI18N
        jMenuItem1.setText("Zaduzivanje Knjige");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Knjige.add(jMenuItem1);

        razduzivanjeKnjigeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/1459100361_bookcase.png"))); // NOI18N
        razduzivanjeKnjigeMenuItem.setText("Razduzivanje knjige");
        razduzivanjeKnjigeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razduzivanjeKnjigeMenuItemActionPerformed(evt);
            }
        });
        Knjige.add(razduzivanjeKnjigeMenuItem);

        jMenuBar1.add(Knjige);

        Pisci.setText("Pisci");

        NoviPisac.setIcon(new javax.swing.ImageIcon("C:\\Users\\boki\\Downloads\\pero.png")); // NOI18N
        NoviPisac.setText("Novi Pisac");
        NoviPisac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoviPisacActionPerformed(evt);
            }
        });
        Pisci.add(NoviPisac);

        PregledPisaca.setIcon(new javax.swing.ImageIcon("C:\\Users\\boki\\Downloads\\Notepad-Bloc-notes-2-icon.png")); // NOI18N
        PregledPisaca.setText("Pregled Pisaca");
        PregledPisaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PregledPisacaActionPerformed(evt);
            }
        });
        Pisci.add(PregledPisaca);

        PregledKnjigaPoPiscu.setIcon(new javax.swing.ImageIcon("C:\\Users\\boki\\Downloads\\Book-edit-icon.png")); // NOI18N
        PregledKnjigaPoPiscu.setText("Pregled Knjiga Po Piscu");
        PregledKnjigaPoPiscu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PregledKnjigaPoPiscuActionPerformed(evt);
            }
        });
        Pisci.add(PregledKnjigaPoPiscu);

        jMenuBar1.add(Pisci);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClanoviNoviClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClanoviNoviClanActionPerformed
        inicijalizujFrame(new NoviClanGUI(), 290, 250, this, "Novi Clan");
    }//GEN-LAST:event_ClanoviNoviClanActionPerformed

    private void PregledRegistrovanihClanovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PregledRegistrovanihClanovaActionPerformed
        inicijalizujFrame(new PregledRegistrovanihClanovaGUI(), 400, 290, this, "Pregled Registrovanih Clanova");
    }//GEN-LAST:event_PregledRegistrovanihClanovaActionPerformed

    private void KnjigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnjigeActionPerformed

    }//GEN-LAST:event_KnjigeActionPerformed

    private void NovaKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaKnjigaActionPerformed
        inicijalizujFrame(new NovaKnjigaGUI(), 290, 300, this, "Nova Knjiga");
    }//GEN-LAST:event_NovaKnjigaActionPerformed

    private void PregledKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PregledKnjigaActionPerformed
        inicijalizujFrame(new PregledKnjigaGUI(), 350, 200, this, "Pregled Knjiga");
    }//GEN-LAST:event_PregledKnjigaActionPerformed

    private void KnjigePregledIznajmljenihKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnjigePregledIznajmljenihKnjigaActionPerformed
        inicijalizujFrame(new PregledIznajmljenihKnjigaGUI(), 500, 400, this, "Pregled Iznajmljenih Knjiga");
    }//GEN-LAST:event_KnjigePregledIznajmljenihKnjigaActionPerformed

    private void NovaKategorijaKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaKategorijaKnjigaActionPerformed
        inicijalizujFrame(new NovaKategorijaKnjigaGUI(), 270, 100, this, "Nova Kategorija");
    }//GEN-LAST:event_NovaKategorijaKnjigaActionPerformed

    private void NoviPisacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoviPisacActionPerformed
        inicijalizujFrame(new NoviPisacGUI(), 290, 250, this, "Novi Pisac");
    }//GEN-LAST:event_NoviPisacActionPerformed

    private void PregledPisacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PregledPisacaActionPerformed

        inicijalizujFrame(new PregledPisacaGUI(), 290, 250, this, "Lista Pisaca");

    }//GEN-LAST:event_PregledPisacaActionPerformed

    private void PregledKnjigaPoPiscuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PregledKnjigaPoPiscuActionPerformed
        inicijalizujFrame(new PregledKnjigaPoPiscuGUI(), 320, 220, this, "Pregled Knjiga Po Piscu");
    }//GEN-LAST:event_PregledKnjigaPoPiscuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        inicijalizujFrame(new ZaduzivanjeKnjigaGUI(), 380, 260, this, "Zaduzivanje Knjiga");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void razduzivanjeKnjigeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razduzivanjeKnjigeMenuItemActionPerformed
        inicijalizujFrame(new RazduzivanjeKnjigeGUI(), 500, 400, this, "Razduzivanje knjige");
    }//GEN-LAST:event_razduzivanjeKnjigeMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Clanovi;
    private javax.swing.JMenuItem ClanoviNoviClan;
    private javax.swing.JMenu Knjige;
    private javax.swing.JMenuItem KnjigePregledIznajmljenihKnjiga;
    private javax.swing.JMenuItem NovaKategorijaKnjiga;
    private javax.swing.JMenuItem NovaKnjiga;
    private javax.swing.JMenuItem NoviPisac;
    private javax.swing.JMenu Pisci;
    private javax.swing.JMenuItem PregledKnjiga;
    private javax.swing.JMenuItem PregledKnjigaPoPiscu;
    private javax.swing.JMenuItem PregledPisaca;
    private javax.swing.JMenuItem PregledRegistrovanihClanova;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem razduzivanjeKnjigeMenuItem;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Biblioteka.png")));

    }

    private void setDialog() {
        JDialog dialog = new JDialog();
        dialog.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Biblioteka.png")));

    }

}
