/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import db.KonekcijaSaBazom;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Kategorija;
import model.Knjiga;
import model.Pisac;


public class NovaKnjigaGUI extends javax.swing.JFrame {

    private KonekcijaSaBazom db;

    public NovaKnjigaGUI() {
        initComponents();
        db = new KonekcijaSaBazom();
        
        List<Pisac> pisci = db.vratiSvePisce();
        cbPisac.removeAllItems();
        for(Pisac pisac : pisci){
            cbPisac.addItem(pisac);
        }
        
        List<Kategorija> kategorije = db.vratiSveKategorije();
        cbKategorije.removeAllItems();
        for(Kategorija kategorija : kategorije){
            cbKategorije.addItem(kategorija);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNovaKnjigaNaslov = new javax.swing.JTextField();
        tfNovaKnjigaIzdavac = new javax.swing.JTextField();
        lbNovaKnjiga = new javax.swing.JLabel();
        lbNovaKnjigaZanr = new javax.swing.JLabel();
        lbNovaKnjigaIzdavac = new javax.swing.JLabel();
        okNovaKnjiga = new javax.swing.JButton();
        cancelNovaKnjiga = new javax.swing.JButton();
        cbPisac = new javax.swing.JComboBox();
        lbNovaKnjigaIzdavac1 = new javax.swing.JLabel();
        cbKategorije = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbNovaKnjiga.setText("Naslov");

        lbNovaKnjigaZanr.setText("Zanr");

        lbNovaKnjigaIzdavac.setText("Izdavac");

        okNovaKnjiga.setText("Ok");
        okNovaKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okNovaKnjigaActionPerformed(evt);
            }
        });

        cancelNovaKnjiga.setText("Cancel");
        cancelNovaKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNovaKnjigaActionPerformed(evt);
            }
        });

        cbPisac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbNovaKnjigaIzdavac1.setText("Pisac");

        cbKategorije.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(okNovaKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelNovaKnjiga))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbNovaKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfNovaKnjigaNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbNovaKnjigaIzdavac, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(lbNovaKnjigaZanr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNovaKnjigaIzdavac, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(cbKategorije, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNovaKnjigaIzdavac1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(cbPisac, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNovaKnjigaNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNovaKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbNovaKnjigaZanr, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbKategorije)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNovaKnjigaIzdavac, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNovaKnjigaIzdavac, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPisac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNovaKnjigaIzdavac1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelNovaKnjiga)
                    .addComponent(okNovaKnjiga))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okNovaKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okNovaKnjigaActionPerformed
        String naslov = tfNovaKnjigaNaslov.getText();
        Kategorija kategorija = (Kategorija) cbKategorije.getSelectedItem();
        String izdavac = tfNovaKnjigaIzdavac.getText();
        Pisac pisac = (Pisac) cbPisac.getSelectedItem();
        boolean success = db.dodajKnjigu(new Knjiga(naslov, pisac, kategorija, izdavac));
        if (success) {
            JOptionPane.showMessageDialog(new JFrame(), "Knjiga sacuvana", "Dialog", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Knjiga nije sacuvana", "Dialog", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_okNovaKnjigaActionPerformed

    private void cancelNovaKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNovaKnjigaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelNovaKnjigaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaKnjigaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaKnjigaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaKnjigaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaKnjigaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaKnjigaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelNovaKnjiga;
    private javax.swing.JComboBox cbKategorije;
    private javax.swing.JComboBox cbPisac;
    private javax.swing.JLabel lbNovaKnjiga;
    private javax.swing.JLabel lbNovaKnjigaIzdavac;
    private javax.swing.JLabel lbNovaKnjigaIzdavac1;
    private javax.swing.JLabel lbNovaKnjigaZanr;
    private javax.swing.JButton okNovaKnjiga;
    private javax.swing.JTextField tfNovaKnjigaIzdavac;
    private javax.swing.JTextField tfNovaKnjigaNaslov;
    // End of variables declaration//GEN-END:variables
}
