/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import db.KonekcijaSaBazom;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Kategorija;
import model.Pisac;

/**
 *
 * @author boki
 */
public class NovaKategorijaKnjigaGUI extends javax.swing.JFrame {

    KonekcijaSaBazom db;

    public NovaKategorijaKnjigaGUI() {
        db = new KonekcijaSaBazom();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNovaKategorijaKnjigaNaziv = new javax.swing.JLabel();
        tfNovaKategorijaKnjigaNaslov = new javax.swing.JTextField();
        okNovaKategorijaKnjiga = new javax.swing.JButton();
        cancelNovaKategorijaKnjiga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbNovaKategorijaKnjigaNaziv.setText("Naziv");

        okNovaKategorijaKnjiga.setText("OK");
        okNovaKategorijaKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okNovaKategorijaKnjigaActionPerformed(evt);
            }
        });

        cancelNovaKategorijaKnjiga.setText("Cancel");
        cancelNovaKategorijaKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNovaKategorijaKnjigaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNovaKategorijaKnjigaNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNovaKategorijaKnjigaNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okNovaKategorijaKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelNovaKategorijaKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNovaKategorijaKnjigaNaziv)
                    .addComponent(tfNovaKategorijaKnjigaNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okNovaKategorijaKnjiga)
                    .addComponent(cancelNovaKategorijaKnjiga))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okNovaKategorijaKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okNovaKategorijaKnjigaActionPerformed
        String naslov = tfNovaKategorijaKnjigaNaslov.getText();

        boolean success = db.dodajKategoriju(new Kategorija(naslov));
        if (success) {
            JOptionPane.showMessageDialog(new JFrame(), "Kategorija sacuvana", "Dialog", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Kategorija nije sacuvana", "Dialog", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_okNovaKategorijaKnjigaActionPerformed
    }
    private void cancelNovaKategorijaKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNovaKategorijaKnjigaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelNovaKategorijaKnjigaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaKategorijaKnjigaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaKategorijaKnjigaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaKategorijaKnjigaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaKategorijaKnjigaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaKategorijaKnjigaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelNovaKategorijaKnjiga;
    private javax.swing.JLabel lbNovaKategorijaKnjigaNaziv;
    private javax.swing.JButton okNovaKategorijaKnjiga;
    private javax.swing.JTextField tfNovaKategorijaKnjigaNaslov;
    // End of variables declaration//GEN-END:variables
}
